// ─────────────────────────────────────────────────────────────────────────────
// GENERATED by scripts/sync-fixtures.mjs — DO NOT EDIT BY HAND.
// Edit convex/fixtures/*.html or convex/fixtures/golden/*.json, then run
//   npm run fixtures:sync
// tests/unit/fixtures-parse.test.ts fails if this file is stale.
// ─────────────────────────────────────────────────────────────────────────────
import type {
  ExtractedFields,
  CaseType,
  ConflictKind,
  FetchStatus,
  IdentityMismatchReason,
  PrivilegeReason,
} from "../contract";

export type FixtureExpectedOutcome =
  | { disposition: "confirmed" }
  | {
      disposition: "conflict";
      case_type: CaseType;
      detected_types: ConflictKind[];
      mismatch_reason?: IdentityMismatchReason;
      privilege_reason?: PrivilegeReason;
    }
  | { disposition: "unconfirmed"; fetch_status: FetchStatus };

export interface Fixture {
  id: string;
  /** verbatim board-page body served by fetch_board_page(mode:"fixture") */
  html: string;
  /** golden ExtractedFields; null when the page is not extractable (block / 404) */
  expected_fields: ExtractedFields | null;
  expected_outcome: FixtureExpectedOutcome;
  /** what fetch_board_page(mode:"fixture") reports for this fixture */
  fetch_status: FetchStatus;
  fetch_http_code: number;
  note?: string;
}

export const FIXTURES = {
  "active_clean": {
    "id": "active_clean",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>License Verification — Board of Registered Nursing</title>\n</head>\n<body>\n  <main>\n    <h1>California Department of Consumer Affairs</h1>\n    <h2>Board of Registered Nursing — License Details</h2>\n    <p class=\"disclaimer\">This information is provided as a public service. Synthetic fixture record — not a live board response.</p>\n    <table class=\"license-detail\">\n      <tbody>\n        <tr><th>Licensee Name</th><td>Maria S. Gomez</td></tr>\n        <tr><th>License Number</th><td>RN-4471102</td></tr>\n        <tr><th>License Type</th><td>Registered Nurse (RN)</td></tr>\n        <tr><th>License Status</th><td>Active</td></tr>\n        <tr><th>Issue Date</th><td>2019-06-14</td></tr>\n        <tr><th>Expiration Date</th><td>2026-06-30</td></tr>\n        <tr><th>License Classification</th><td>Single State</td></tr>\n        <tr><th>Primary State of Residence</th><td>NY</td></tr>\n        <tr><th>Disciplinary Action</th><td>None on record</td></tr>\n      </tbody>\n    </table>\n  </main>\n</body>\n</html>\n",
    "expected_fields": {
      "licensee_name": "Maria S. Gomez",
      "license_number": "RN-4471102",
      "status_word": "Active",
      "status_normalized": "active",
      "issue_date": "2019-06-14",
      "expire_date": "2026-06-30",
      "privilege_type": "single_state",
      "primary_state_of_residence": "NY",
      "extraction_confidence": "high"
    },
    "expected_outcome": {
      "disposition": "confirmed"
    },
    "fetch_status": "ok",
    "fetch_http_code": 200
  },
  "blocked_page": {
    "id": "blocked_page",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>Verifying you are human</title>\n</head>\n<body>\n  <main>\n    <h1>Unusual traffic from your network</h1>\n    <p>Our systems have detected unusual traffic from your computer network. This\n       page checks to see whether it's really you sending the requests, and not a\n       robot.</p>\n    <p>To continue, please complete the security check below.</p>\n    <div class=\"g-recaptcha\" data-sitekey=\"synthetic-fixture-sitekey\"></div>\n    <noscript>Please enable JavaScript and cookies to continue.</noscript>\n    <p class=\"ray\">Reference ID: 0x7f3a9c2 · synthetic fixture — not a live board response</p>\n  </main>\n</body>\n</html>\n",
    "expected_fields": null,
    "expected_outcome": {
      "disposition": "unconfirmed",
      "fetch_status": "blocked"
    },
    "fetch_status": "blocked",
    "fetch_http_code": 403
  },
  "flip_active": {
    "id": "flip_active",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>License Verification — Board of Registered Nursing</title>\n</head>\n<body>\n  <main>\n    <h1>California Department of Consumer Affairs</h1>\n    <h2>Board of Registered Nursing — License Details</h2>\n    <p class=\"disclaimer\">Synthetic fixture record — not a live board response.</p>\n    <table class=\"license-detail\">\n      <tbody>\n        <tr><th>Licensee Name</th><td>Maria S. Gomez</td></tr>\n        <tr><th>License Number</th><td>RN-4471102</td></tr>\n        <tr><th>License Type</th><td>Registered Nurse (RN)</td></tr>\n        <tr><th>License Status</th><td>Active</td></tr>\n        <tr><th>Issue Date</th><td>2019-06-14</td></tr>\n        <tr><th>Expiration Date</th><td>2026-06-30</td></tr>\n        <tr><th>License Classification</th><td>Single State</td></tr>\n        <tr><th>Primary State of Residence</th><td>NY</td></tr>\n        <tr><th>Disciplinary Action</th><td>None on record</td></tr>\n      </tbody>\n    </table>\n  </main>\n</body>\n</html>\n",
    "expected_fields": {
      "licensee_name": "Maria S. Gomez",
      "license_number": "RN-4471102",
      "status_word": "Active",
      "status_normalized": "active",
      "issue_date": "2019-06-14",
      "expire_date": "2026-06-30",
      "privilege_type": "single_state",
      "primary_state_of_residence": "NY",
      "extraction_confidence": "high"
    },
    "expected_outcome": {
      "disposition": "confirmed"
    },
    "fetch_status": "ok",
    "fetch_http_code": 200,
    "note": "T1 of the active→expired flip pair"
  },
  "flip_expired": {
    "id": "flip_expired",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>License Verification — Board of Registered Nursing</title>\n</head>\n<body>\n  <main>\n    <h1>California Department of Consumer Affairs</h1>\n    <h2>Board of Registered Nursing — License Details</h2>\n    <p class=\"disclaimer\">Synthetic fixture record — not a live board response.</p>\n    <table class=\"license-detail\">\n      <tbody>\n        <tr><th>Licensee Name</th><td>Maria S. Gomez</td></tr>\n        <tr><th>License Number</th><td>RN-4471102</td></tr>\n        <tr><th>License Type</th><td>Registered Nurse (RN)</td></tr>\n        <tr><th>License Status</th><td>Expired</td></tr>\n        <tr><th>Issue Date</th><td>2019-06-14</td></tr>\n        <tr><th>Expiration Date</th><td>2024-06-30</td></tr>\n        <tr><th>License Classification</th><td>Single State</td></tr>\n        <tr><th>Primary State of Residence</th><td>NY</td></tr>\n        <tr><th>Disciplinary Action</th><td>None on record</td></tr>\n      </tbody>\n    </table>\n  </main>\n</body>\n</html>\n",
    "expected_fields": {
      "licensee_name": "Maria S. Gomez",
      "license_number": "RN-4471102",
      "status_word": "Expired",
      "status_normalized": "expired",
      "issue_date": "2019-06-14",
      "expire_date": "2024-06-30",
      "privilege_type": "single_state",
      "primary_state_of_residence": "NY",
      "extraction_confidence": "high"
    },
    "expected_outcome": {
      "disposition": "conflict",
      "case_type": "status",
      "detected_types": [
        "status"
      ]
    },
    "fetch_status": "ok",
    "fetch_http_code": 200,
    "note": "T2 of the flip; requires a prior confirmed `active` snapshot for the diff"
  },
  "mc_t1": {
    "id": "mc_t1",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>License Verification — Board of Registered Nursing</title>\n</head>\n<body>\n  <main>\n    <h1>California Department of Consumer Affairs</h1>\n    <h2>Board of Registered Nursing — License Details</h2>\n    <p class=\"disclaimer\">Synthetic fixture record — not a live board response.</p>\n    <table class=\"license-detail\">\n      <tbody>\n        <tr><th>Licensee Name</th><td>Karen M. Blackwood</td></tr>\n        <tr><th>License Number</th><td>RN-6650391</td></tr>\n        <tr><th>License Type</th><td>Registered Nurse (RN)</td></tr>\n        <tr><th>License Status</th><td>Active</td></tr>\n        <tr><th>Issue Date</th><td>2016-07-12</td></tr>\n        <tr><th>Expiration Date</th><td>2026-09-30</td></tr>\n        <tr><th>License Classification</th><td>Single State</td></tr>\n        <tr><th>Primary State of Residence</th><td>CA</td></tr>\n        <tr><th>Disciplinary Action</th><td>None on record</td></tr>\n      </tbody>\n    </table>\n  </main>\n</body>\n</html>\n",
    "expected_fields": {
      "licensee_name": "Karen M. Blackwood",
      "license_number": "RN-6650391",
      "status_word": "Active",
      "status_normalized": "active",
      "issue_date": "2016-07-12",
      "expire_date": "2026-09-30",
      "privilege_type": "single_state",
      "primary_state_of_residence": "CA",
      "extraction_confidence": "high"
    },
    "expected_outcome": {
      "disposition": "confirmed"
    },
    "fetch_status": "ok",
    "fetch_http_code": 200,
    "note": "clean single-state T1 for the multi-conflict sequence"
  },
  "multi_conflict": {
    "id": "multi_conflict",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>License Verification — Board of Registered Nursing</title>\n</head>\n<body>\n  <main>\n    <h1>California Department of Consumer Affairs</h1>\n    <h2>Board of Registered Nursing — License Details</h2>\n    <p class=\"disclaimer\">Synthetic fixture record — not a live board response.</p>\n    <table class=\"license-detail\">\n      <tbody>\n        <tr><th>Licensee Name</th><td>Karen M. Blackwood</td></tr>\n        <tr><th>License Number</th><td>RN-6650391</td></tr>\n        <tr><th>License Type</th><td>Registered Nurse (RN)</td></tr>\n        <tr><th>License Status</th><td>Expired</td></tr>\n        <tr><th>Issue Date</th><td>2016-07-12</td></tr>\n        <tr><th>Expiration Date</th><td>2024-09-30</td></tr>\n        <tr><th>License Classification</th><td>Multistate</td></tr>\n        <tr><th>Primary State of Residence</th><td>CA</td></tr>\n        <tr><th>Compact Privilege</th><td>Nurse Licensure Compact (multistate)</td></tr>\n        <tr><th>Disciplinary Action</th><td>None on record</td></tr>\n      </tbody>\n    </table>\n  </main>\n</body>\n</html>\n",
    "expected_fields": {
      "licensee_name": "Karen M. Blackwood",
      "license_number": "RN-6650391",
      "status_word": "Expired",
      "status_normalized": "expired",
      "issue_date": "2016-07-12",
      "expire_date": "2024-09-30",
      "privilege_type": "multistate",
      "primary_state_of_residence": "CA",
      "extraction_confidence": "high"
    },
    "expected_outcome": {
      "disposition": "conflict",
      "case_type": "privilege",
      "detected_types": [
        "privilege",
        "status"
      ],
      "privilege_reason": "multistate_but_assignment_state_mismatch"
    },
    "fetch_status": "ok",
    "fetch_http_code": 200,
    "note": "expired AND multistate-into-non-NLC on the same fetch; ONE case, type=privilege (D-10a), detail keeps both"
  },
  "name_changed": {
    "id": "name_changed",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>License Verification — Board of Registered Nursing</title>\n</head>\n<body>\n  <main>\n    <h1>California Department of Consumer Affairs</h1>\n    <h2>Board of Registered Nursing — License Details</h2>\n    <p class=\"disclaimer\">Synthetic fixture record — not a live board response.</p>\n    <table class=\"license-detail\">\n      <tbody>\n        <tr><th>Licensee Name</th><td>Sarah A. Whitfield</td></tr>\n        <tr><th>License Number</th><td>RN-2298475</td></tr>\n        <tr><th>License Type</th><td>Registered Nurse (RN)</td></tr>\n        <tr><th>License Status</th><td>Active</td></tr>\n        <tr><th>Issue Date</th><td>2015-09-20</td></tr>\n        <tr><th>Expiration Date</th><td>2026-09-30</td></tr>\n        <tr><th>License Classification</th><td>Single State</td></tr>\n        <tr><th>Primary State of Residence</th><td>NY</td></tr>\n        <tr><th>Former Name On Record</th><td>Sarah A. Jenkins</td></tr>\n        <tr><th>Disciplinary Action</th><td>None on record</td></tr>\n      </tbody>\n    </table>\n  </main>\n</body>\n</html>\n",
    "expected_fields": {
      "licensee_name": "Sarah A. Whitfield",
      "license_number": "RN-2298475",
      "status_word": "Active",
      "status_normalized": "active",
      "issue_date": "2015-09-20",
      "expire_date": "2026-09-30",
      "privilege_type": "single_state",
      "primary_state_of_residence": "NY",
      "extraction_confidence": "high"
    },
    "expected_outcome": {
      "disposition": "conflict",
      "case_type": "identity",
      "detected_types": [
        "identity"
      ],
      "mismatch_reason": "legal_name_change"
    },
    "fetch_status": "ok",
    "fetch_http_code": 200,
    "note": "surname changed vs worker.name_registered; number still matches"
  },
  "name_ok": {
    "id": "name_ok",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>License Verification — Board of Registered Nursing</title>\n</head>\n<body>\n  <main>\n    <h1>California Department of Consumer Affairs</h1>\n    <h2>Board of Registered Nursing — License Details</h2>\n    <p class=\"disclaimer\">Synthetic fixture record — not a live board response.</p>\n    <table class=\"license-detail\">\n      <tbody>\n        <tr><th>Licensee Name</th><td>Sarah A. Jenkins</td></tr>\n        <tr><th>License Number</th><td>RN-2298475</td></tr>\n        <tr><th>License Type</th><td>Registered Nurse (RN)</td></tr>\n        <tr><th>License Status</th><td>Active</td></tr>\n        <tr><th>Issue Date</th><td>2015-09-20</td></tr>\n        <tr><th>Expiration Date</th><td>2026-09-30</td></tr>\n        <tr><th>License Classification</th><td>Single State</td></tr>\n        <tr><th>Primary State of Residence</th><td>NY</td></tr>\n        <tr><th>Disciplinary Action</th><td>None on record</td></tr>\n      </tbody>\n    </table>\n  </main>\n</body>\n</html>\n",
    "expected_fields": {
      "licensee_name": "Sarah A. Jenkins",
      "license_number": "RN-2298475",
      "status_word": "Active",
      "status_normalized": "active",
      "issue_date": "2015-09-20",
      "expire_date": "2026-09-30",
      "privilege_type": "single_state",
      "primary_state_of_residence": "NY",
      "extraction_confidence": "high"
    },
    "expected_outcome": {
      "disposition": "confirmed"
    },
    "fetch_status": "ok",
    "fetch_http_code": 200,
    "note": "clean T1 for the name-change sequence"
  },
  "name_wrong_person": {
    "id": "name_wrong_person",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>License Verification — Board of Registered Nursing</title>\n</head>\n<body>\n  <main>\n    <h1>California Department of Consumer Affairs</h1>\n    <h2>Board of Registered Nursing — License Details</h2>\n    <p class=\"disclaimer\">Synthetic fixture record — not a live board response.</p>\n    <table class=\"license-detail\">\n      <tbody>\n        <tr><th>Licensee Name</th><td>Michael J. Okonkwo</td></tr>\n        <tr><th>License Number</th><td>RN-2298475</td></tr>\n        <tr><th>License Type</th><td>Registered Nurse (RN)</td></tr>\n        <tr><th>License Status</th><td>Active</td></tr>\n        <tr><th>Issue Date</th><td>2015-09-20</td></tr>\n        <tr><th>Expiration Date</th><td>2026-09-30</td></tr>\n        <tr><th>License Classification</th><td>Single State</td></tr>\n        <tr><th>Primary State of Residence</th><td>NY</td></tr>\n        <tr><th>Disciplinary Action</th><td>None on record</td></tr>\n      </tbody>\n    </table>\n  </main>\n</body>\n</html>\n",
    "expected_fields": {
      "licensee_name": "Michael J. Okonkwo",
      "license_number": "RN-2298475",
      "status_word": "Active",
      "status_normalized": "active",
      "issue_date": "2015-09-20",
      "expire_date": "2026-09-30",
      "privilege_type": "single_state",
      "primary_state_of_residence": "NY",
      "extraction_confidence": "high"
    },
    "expected_outcome": {
      "disposition": "conflict",
      "case_type": "identity",
      "detected_types": [
        "identity"
      ],
      "mismatch_reason": "wrong_person"
    },
    "fetch_status": "ok",
    "fetch_http_code": 200,
    "note": "different person entirely; number matches (impostor pattern, F2)"
  },
  "not_found": {
    "id": "not_found",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>404 — Record Not Found</title>\n</head>\n<body>\n  <main>\n    <h1>404 — Not Found</h1>\n    <p>The requested license record could not be found. It may have been removed,\n       or the license number may be incorrect.</p>\n    <p>Please return to the <a href=\"/search\">license search</a> and try again.</p>\n    <p class=\"ref\">Synthetic fixture — not a live board response.</p>\n  </main>\n</body>\n</html>\n",
    "expected_fields": null,
    "expected_outcome": {
      "disposition": "unconfirmed",
      "fetch_status": "http_error"
    },
    "fetch_status": "http_error",
    "fetch_http_code": 404
  },
  "privilege_ok": {
    "id": "privilege_ok",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>License Verification — Board of Registered Nursing</title>\n</head>\n<body>\n  <main>\n    <h1>California Department of Consumer Affairs</h1>\n    <h2>Board of Registered Nursing — License Details</h2>\n    <p class=\"disclaimer\">Synthetic fixture record — not a live board response.</p>\n    <table class=\"license-detail\">\n      <tbody>\n        <tr><th>Licensee Name</th><td>David R. Okafor</td></tr>\n        <tr><th>License Number</th><td>RN-7781340</td></tr>\n        <tr><th>License Type</th><td>Registered Nurse (RN)</td></tr>\n        <tr><th>License Status</th><td>Active</td></tr>\n        <tr><th>Issue Date</th><td>2018-11-05</td></tr>\n        <tr><th>Expiration Date</th><td>2026-11-30</td></tr>\n        <tr><th>License Classification</th><td>Single State</td></tr>\n        <tr><th>Primary State of Residence</th><td>CA</td></tr>\n        <tr><th>Disciplinary Action</th><td>None on record</td></tr>\n      </tbody>\n    </table>\n  </main>\n</body>\n</html>\n",
    "expected_fields": {
      "licensee_name": "David R. Okafor",
      "license_number": "RN-7781340",
      "status_word": "Active",
      "status_normalized": "active",
      "issue_date": "2018-11-05",
      "expire_date": "2026-11-30",
      "privilege_type": "single_state",
      "primary_state_of_residence": "CA",
      "extraction_confidence": "high"
    },
    "expected_outcome": {
      "disposition": "confirmed"
    },
    "fetch_status": "ok",
    "fetch_http_code": 200,
    "note": "clean single-state T1 for the privilege sequence"
  },
  "privilege_violation": {
    "id": "privilege_violation",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>License Verification — Board of Registered Nursing</title>\n</head>\n<body>\n  <main>\n    <h1>California Department of Consumer Affairs</h1>\n    <h2>Board of Registered Nursing — License Details</h2>\n    <p class=\"disclaimer\">Synthetic fixture record — not a live board response.</p>\n    <table class=\"license-detail\">\n      <tbody>\n        <tr><th>Licensee Name</th><td>David R. Okafor</td></tr>\n        <tr><th>License Number</th><td>RN-7781340</td></tr>\n        <tr><th>License Type</th><td>Registered Nurse (RN)</td></tr>\n        <tr><th>License Status</th><td>Active</td></tr>\n        <tr><th>Issue Date</th><td>2018-11-05</td></tr>\n        <tr><th>Expiration Date</th><td>2026-11-30</td></tr>\n        <tr><th>License Classification</th><td>Multistate</td></tr>\n        <tr><th>Primary State of Residence</th><td>CA</td></tr>\n        <tr><th>Compact Privilege</th><td>Nurse Licensure Compact (multistate)</td></tr>\n        <tr><th>Disciplinary Action</th><td>None on record</td></tr>\n      </tbody>\n    </table>\n  </main>\n</body>\n</html>\n",
    "expected_fields": {
      "licensee_name": "David R. Okafor",
      "license_number": "RN-7781340",
      "status_word": "Active",
      "status_normalized": "active",
      "issue_date": "2018-11-05",
      "expire_date": "2026-11-30",
      "privilege_type": "multistate",
      "primary_state_of_residence": "CA",
      "extraction_confidence": "high"
    },
    "expected_outcome": {
      "disposition": "conflict",
      "case_type": "privilege",
      "detected_types": [
        "privilege"
      ],
      "privilege_reason": "multistate_but_assignment_state_mismatch"
    },
    "fetch_status": "ok",
    "fetch_http_code": 200,
    "note": "multistate license; assignment state is not an NLC member"
  },
  "suspension_seq_1": {
    "id": "suspension_seq_1",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>License Verification — Board of Registered Nursing</title>\n</head>\n<body>\n  <main>\n    <h1>California Department of Consumer Affairs</h1>\n    <h2>Board of Registered Nursing — License Details</h2>\n    <p class=\"disclaimer\">Synthetic fixture record (week 1 of 6) — not a live board response.</p>\n    <table class=\"license-detail\">\n      <tbody>\n        <tr><th>Licensee Name</th><td>Linda K. Park</td></tr>\n        <tr><th>License Number</th><td>RN-5540218</td></tr>\n        <tr><th>License Type</th><td>Registered Nurse (RN)</td></tr>\n        <tr><th>License Status</th><td>Active</td></tr>\n        <tr><th>Issue Date</th><td>2017-03-01</td></tr>\n        <tr><th>Expiration Date</th><td>2026-02-28</td></tr>\n        <tr><th>License Classification</th><td>Single State</td></tr>\n        <tr><th>Primary State of Residence</th><td>NY</td></tr>\n        <tr><th>Disciplinary Action</th><td>None on record</td></tr>\n      </tbody>\n    </table>\n  </main>\n</body>\n</html>\n",
    "expected_fields": {
      "licensee_name": "Linda K. Park",
      "license_number": "RN-5540218",
      "status_word": "Active",
      "status_normalized": "active",
      "issue_date": "2017-03-01",
      "expire_date": "2026-02-28",
      "privilege_type": "single_state",
      "primary_state_of_residence": "NY",
      "extraction_confidence": "high"
    },
    "expected_outcome": {
      "disposition": "confirmed"
    },
    "fetch_status": "ok",
    "fetch_http_code": 200
  },
  "suspension_seq_2": {
    "id": "suspension_seq_2",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>License Verification — Board of Registered Nursing</title>\n</head>\n<body>\n  <main>\n    <h1>California Department of Consumer Affairs</h1>\n    <h2>Board of Registered Nursing — License Details</h2>\n    <p class=\"disclaimer\">Synthetic fixture record (week 3 of 6) — not a live board response.</p>\n    <table class=\"license-detail\">\n      <tbody>\n        <tr><th>Licensee Name</th><td>Linda K. Park</td></tr>\n        <tr><th>License Number</th><td>RN-5540218</td></tr>\n        <tr><th>License Type</th><td>Registered Nurse (RN)</td></tr>\n        <tr><th>License Status</th><td>Active</td></tr>\n        <tr><th>Issue Date</th><td>2017-03-01</td></tr>\n        <tr><th>Expiration Date</th><td>2026-02-28</td></tr>\n        <tr><th>License Classification</th><td>Single State</td></tr>\n        <tr><th>Primary State of Residence</th><td>NY</td></tr>\n        <tr><th>Disciplinary Action</th><td>None on record</td></tr>\n      </tbody>\n    </table>\n  </main>\n</body>\n</html>\n",
    "expected_fields": {
      "licensee_name": "Linda K. Park",
      "license_number": "RN-5540218",
      "status_word": "Active",
      "status_normalized": "active",
      "issue_date": "2017-03-01",
      "expire_date": "2026-02-28",
      "privilege_type": "single_state",
      "primary_state_of_residence": "NY",
      "extraction_confidence": "high"
    },
    "expected_outcome": {
      "disposition": "confirmed"
    },
    "fetch_status": "ok",
    "fetch_http_code": 200
  },
  "suspension_seq_3": {
    "id": "suspension_seq_3",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>License Verification — Board of Registered Nursing</title>\n</head>\n<body>\n  <main>\n    <h1>California Department of Consumer Affairs</h1>\n    <h2>Board of Registered Nursing — License Details</h2>\n    <p class=\"disclaimer\">Synthetic fixture record (week 5 of 6) — not a live board response.</p>\n    <table class=\"license-detail\">\n      <tbody>\n        <tr><th>Licensee Name</th><td>Linda K. Park</td></tr>\n        <tr><th>License Number</th><td>RN-5540218</td></tr>\n        <tr><th>License Type</th><td>Registered Nurse (RN)</td></tr>\n        <tr><th>License Status</th><td>Active</td></tr>\n        <tr><th>Issue Date</th><td>2017-03-01</td></tr>\n        <tr><th>Expiration Date</th><td>2026-02-28</td></tr>\n        <tr><th>License Classification</th><td>Single State</td></tr>\n        <tr><th>Primary State of Residence</th><td>NY</td></tr>\n        <tr><th>Disciplinary Action</th><td>None on record</td></tr>\n      </tbody>\n    </table>\n  </main>\n</body>\n</html>\n",
    "expected_fields": {
      "licensee_name": "Linda K. Park",
      "license_number": "RN-5540218",
      "status_word": "Active",
      "status_normalized": "active",
      "issue_date": "2017-03-01",
      "expire_date": "2026-02-28",
      "privilege_type": "single_state",
      "primary_state_of_residence": "NY",
      "extraction_confidence": "high"
    },
    "expected_outcome": {
      "disposition": "confirmed"
    },
    "fetch_status": "ok",
    "fetch_http_code": 200
  },
  "suspension_seq_4": {
    "id": "suspension_seq_4",
    "html": "<!doctype html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\" />\n  <title>License Verification — Board of Registered Nursing</title>\n</head>\n<body>\n  <main>\n    <h1>California Department of Consumer Affairs</h1>\n    <h2>Board of Registered Nursing — License Details</h2>\n    <p class=\"disclaimer\">Synthetic fixture record (week 6 of 6) — not a live board response.</p>\n    <table class=\"license-detail\">\n      <tbody>\n        <tr><th>Licensee Name</th><td>Linda K. Park</td></tr>\n        <tr><th>License Number</th><td>RN-5540218</td></tr>\n        <tr><th>License Type</th><td>Registered Nurse (RN)</td></tr>\n        <tr><th>License Status</th><td>Suspended</td></tr>\n        <tr><th>Issue Date</th><td>2017-03-01</td></tr>\n        <tr><th>Expiration Date</th><td>2026-02-28</td></tr>\n        <tr><th>License Classification</th><td>Single State</td></tr>\n        <tr><th>Primary State of Residence</th><td>NY</td></tr>\n        <tr><th>Disciplinary Action</th><td>License suspended effective 2026-02-09 pending board investigation (Case No. 2026-01187).</td></tr>\n      </tbody>\n    </table>\n  </main>\n</body>\n</html>\n",
    "expected_fields": {
      "licensee_name": "Linda K. Park",
      "license_number": "RN-5540218",
      "status_word": "Suspended",
      "status_normalized": "suspended",
      "issue_date": "2017-03-01",
      "expire_date": "2026-02-28",
      "privilege_type": "single_state",
      "primary_state_of_residence": "NY",
      "extraction_confidence": "high"
    },
    "expected_outcome": {
      "disposition": "conflict",
      "case_type": "status",
      "detected_types": [
        "status"
      ]
    },
    "fetch_status": "ok",
    "fetch_http_code": 200,
    "note": "6-week suspension: 4th scheduled re-check; prior confirmed = active"
  }
} satisfies Record<string, Fixture>;

export type FixtureId = keyof typeof FIXTURES;

export const FIXTURE_LIST: readonly Fixture[] = Object.values(FIXTURES);

export function getFixture(id: string): Fixture {
  const f = (FIXTURES as Record<string, Fixture>)[id];
  if (!f) throw new Error(`unknown fixture id: ${id}`);
  return f;
}

/** Named demo sequences — Step 10 seeds licenses.fixture_sequence with these. */
export const DEMO_SEQUENCES = {
  "nurse_a": [
    "flip_active",
    "flip_expired"
  ],
  "nurse_b": [
    "name_ok",
    "name_changed"
  ],
  "nurse_c": [
    "privilege_ok",
    "privilege_violation"
  ],
  "nurse_d": [
    "suspension_seq_1",
    "suspension_seq_2",
    "suspension_seq_3",
    "suspension_seq_4"
  ]
} satisfies Record<
  string,
  FixtureId[]
>;
